# Generated by Django 2.1.7 on 2019-03-13 19:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('telefono', models.IntegerField()),
                ('modelo', models.CharField(max_length=60)),
                ('color', models.CharField(max_length=60)),
                ('matricula', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaOperacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cambio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('numero', models.IntegerField(default=0)),
                ('efectivo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descuentoTotal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=25)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicioMembresia', models.DateField(default=datetime.datetime(2019, 3, 13, 19, 30, 59, 393945, tzinfo=utc))),
                ('finalMembresia', models.DateField(default=datetime.datetime(2019, 4, 12, 19, 30, 59, 393945, tzinfo=utc))),
                ('estado', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaOperacion', models.DateTimeField(auto_now_add=True)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observaciones', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=True)),
                ('Membresia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeOperacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMembresia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='operacion',
            name='tipoOperacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.TipoDeOperacion'),
        ),
        migrations.AddField(
            model_name='membresia',
            name='tipoMembresia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.TipoMembresia'),
        ),
        migrations.AddField(
            model_name='facturaoperacion',
            name='operacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clientes.Operacion'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Genero'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Marca'),
        ),
    ]
